[package]
name = "dok"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-dok = { version = "0.1.0", path = "parsers/cargo-dok" }
clap = { version = "4.5.43", features = ["derive"] }
serde_json = "1.0.142"
strum = "0.27.2"
strum_macros = "0.27.2"
